### ISSUE TITLE
Parsing a string of Html

### ISSUE THREAD

**Issue by MikeiLL** [decodelabs/tagged#6]
Hey, @betterthanclay.

Happy Valentine's Day (if it still is for you, or belated if not).

I have an API that's returning a string of HTML that I'd like to parse with Tagged:

```
"<h1>Heading here</h1><p>more stuff</p>"
```

Betting there's a method for that. Hope you don't mind me asking before digging.

**Comment by MikeiLL** [comment]
There it is at the top of the docs. That's embarrassing.

```
$buffer = Html::raw('<span class="test">My span</span>');
```

**Comment by betterthanclay** [comment]
Hi Mike. Haha don't worry, it's easy to miss. As it is, the raw method doesn't do any parsing, it just wraps a string considered to be valid HTML so that if you return it in a generator function, it's not double escaped.

Proper parsing is way way more complicated and not something I've tackled yet.. it might go on the todo list as some point but it's pretty low priority compared to a lot of other planned functionality.

Anyway, it seems like just wrapping it is enough for your case here. All good.
